maestrodata::maestro_plotfile = "fillme";
pp.query("MAESTRO_plotfile", maestrodata::maestro_plotfile);

maestrodata::maestro_modelfile = "fillme";
pp.query("MAESTRO_modelfile", maestrodata::maestro_modelfile);

maestrodata::maestro_npts_model = 0;
pp.query("MAESTRO_npts_model", maestrodata::maestro_npts_model);

maestrodata::maestro_first_species = "fillme";
pp.query("MAESTRO_first_species", maestrodata::maestro_first_species);

maestrodata::maestro_nspec = 0;
pp.query("MAESTRO_nspec", maestrodata::maestro_nspec);

maestrodata::maestro_cutoff_density = -1.0;
pp.query("MAESTRO_cutoff_density", maestrodata::maestro_cutoff_density);

maestrodata::maestro_init_type = 0;
pp.query("MAESTRO_init_type", maestrodata::maestro_init_type);

maestrodata::maestro_spherical = false;
pp.query("MAESTRO_spherical", maestrodata::maestro_spherical);


